# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RodeosCateringProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RodeosCateringProject

pod 'Firebase'
pod 'Firebase/Core'
pod 'FirebaseUI/Auth'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'

  target 'RodeosCateringProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RodeosCateringProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
